Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,3 +26,31 @@ jobs:
         run: | 
           python -m pytest 
 
+      - name: Déploiement via SSH
+        run: |
+          # Install SSH client
+          sudo apt-get update && sudo apt-get install -y openssh-client
+
+          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
+            echo "ERROR: SERVER_HOST secret is not set or empty"
+            exit 1
+          else
+            echo "SERVER_HOST is set"
+          fi
+          
+          # Setup SSH key
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          
+          # Add server to known hosts to avoid host key verification prompt
+          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
+          
+          # Deploy via SSH
+          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
+            cd log430-a25-labo3
+            git pull origin main
+            cd src
+            python3.11 store_manager.py
+          EOF
+
