mettre en commentaire SSH dans ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,28 +29,29 @@ jobs:
         run: |
           python -m pytest
 
-      - name: Déploiement via SSH
-        run: |
-          # Install SSH client
-          sudo apt-get update && sudo apt-get install -y openssh-client
+      #- name: Déploiement via SSH
+      #  run: |
+      #    # Install SSH client
+      #    sudo apt-get update && sudo apt-get install -y openssh-client
 
-          if [ -z "${{ secrets.SSH_SERVER_HOST }}" ]; then
-            echo "ERROR: SSH_SERVER_HOST secret is not set or empty"
-            exit 1
-          else
-            echo "SSH_SERVER_HOST is set"
-          fi
-
-          # Setup SSH key
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-
-          # Add server to known hosts to avoid host key verification prompt
-          ssh-keyscan -H ${{ secrets.SSH_SERVER_HOST }} >> ~/.ssh/known_hosts
-
-          # Deploy via SSH
-          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }} << 'EOF'
-            cd log430-a25-labo0
-            git pull origin main
-          EOF
+#
+#    if [ -z "${{ secrets.SSH_SERVER_HOST }}" ]; then
+#      echo "ERROR: SSH_SERVER_HOST secret is not set or empty"
+#      exit 1
+#    else
+#      echo "SSH_SERVER_HOST is set"
+#    fi
+#
+#    # Setup SSH key
+#    mkdir -p ~/.ssh
+#    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+#    chmod 600 ~/.ssh/id_rsa
+#
+#    # Add server to known hosts to avoid host key verification prompt
+#    ssh-keyscan -H ${{ secrets.SSH_SERVER_HOST }} >> ~/.ssh/known_hosts
+#
+#    # Deploy via SSH
+#    ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }} << 'EOF'
+#      cd log430-a25-labo0
+#      git pull origin main
+#    EOF
